export const VK_GET_FRIENDS_REQUEST = 'VK_GET_FRIENDS_REQUEST';
export const VK_GET_FRIENDS_SUCCESS = 'VK_GET_FRIENDS_SUCCESS';
export const VK_GET_FRIENDS_FAILURE = 'VK_GET_FRIENDS_FAILURE';

export const VK_GET_MUTUAL_FRIENDS_REQUEST = 'VK_GET_MUTUAL_FRIENDS_REQUEST';
export const VK_GET_MUTUAL_FRIENDS_SUCCESS = 'VK_GET_MUTUAL_FRIENDS_SUCCESS';
export const VK_GET_MUTUAL_FRIENDS_FAILURE = 'VK_GET_MUTUAL_FRIENDS_FAILURE';

export const VK_GET_LISTS_REQUEST = 'VK_GETLISTS_REQUEST';
export const VK_GET_LISTS_SUCCESS = 'VK_GETLISTS_SUCCESS';
export const VK_GET_LISTS_FAILURE = 'VK_GETLISTS_FAILURE';